version: "3"

networks:
  observability-stack:
    driver: bridge

volumes:
  prometheus-data: {}
  grafana-data: {}
  loki-data: {}

services:
  node_exporter:
    image: prom/node-exporter:latest
    expose:
      - 9100
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - observability-stack

  container_exporter:
    image: gcr.io/cadvisor/cadvisor:latest
    expose:
      - 8080
    container_name: container-exporter
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - observability-stack

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus-config.yaml:/opt/bitnami/prometheus/conf/prometheus-config.yaml:ro
      - prometheus-data:/opt/bitnami/prometheus/data
    command:
      - '--config.file=/opt/bitnami/prometheus/conf/prometheus-config.yaml'
    networks:
      - observability-stack
    depends_on:
      - container_exporter
      - node_exporter

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - '3100:3100'
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    command:
      - '-config.file=/etc/loki/loki-config.yaml'
    networks:
      - observability-stack

  promtail_agent:
    image: grafana/promtail:latest
    container_name: promtail-agent
    restart: unless-stopped
    volumes:
      - ./config/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  # Optional, if collecting container logs
    command:
      - '-config.file=/etc/promtail/promtail-config.yaml'
    networks:
      - observability-stack
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - observability-stack
    depends_on:
      - prometheus
      - loki


