global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'web-api'
    static_configs:
      - targets: ['app-a:8080']

  - job_name: "container"
    static_configs:
      - targets: ['new-container-exporter:9104']
  # Additional job configs can be added here

